# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20170404_1408'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0002_auto_20170404_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('grams', models.PositiveIntegerField(blank=True, null=True)),
                ('fraction', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.GenericDish')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.DietPlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
