# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_dishlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishlog',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='dishlog',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='dishlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='DishLog',
        ),
    ]
