# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20170405_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayplan',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='dayplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dietplannutrient',
            name='nutrient',
        ),
        migrations.RemoveField(
            model_name='dietplannutrient',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='dietplannutrient',
            name='unit',
        ),
        migrations.DeleteModel(
            name='DayPlan',
        ),
        migrations.DeleteModel(
            name='DietPlan',
        ),
        migrations.DeleteModel(
            name='DietPlanNutrient',
        ),
    ]
