# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('drink', 'drink'), ('snack', 'snack'), ('food', 'food')], default='', max_length=32),
            preserve_default=False,
        ),
    ]
