# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_dish_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='nutrient',
            old_name='unit',
            new_name='dri_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='nutrients_per_unit',
        ),
        migrations.AddField(
            model_name='ingredientnutrient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientnutrient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Nutrient'),
        ),
        migrations.AddField(
            model_name='ingredientnutrient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Unit'),
        ),
    ]
