# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20170316_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammsOfIngredientPerUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='calories_per_unit',
            new_name='calories_per_100_gr',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='grams',
        ),
        migrations.AlterField(
            model_name='dish',
            name='preparation',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AddField(
            model_name='grammsofingredientperunit',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Ingredient'),
        ),
        migrations.AddField(
            model_name='grammsofingredientperunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Unit'),
        ),
    ]
