# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20170317_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayplan',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='day_plans',
        ),
        migrations.RenameField(
            model_name='dishingredient',
            old_name='units',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='type',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='meals',
            field=models.ManyToManyField(to='food.Meal'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='food.Dish'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='food.Ingredient'),
        ),
        migrations.AlterField(
            model_name='grammsofingredientperunit',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grams_per_unit_of_ingredient', to='food.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientnutrient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='food.Ingredient'),
        ),
        migrations.DeleteModel(
            name='DayPlan',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
