# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:40
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20170323_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
