# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20170323_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientnutrient',
            old_name='ammount',
            new_name='amount_per_100_gr',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='calories_per_100_gr',
        ),
        migrations.AddField(
            model_name='nutrient',
            name='type',
            field=models.CharField(choices=[('macro', 'macro'), ('micro', 'micro'), ('energy', 'energy')], default='micro', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER'), ('SUPPER', 'SUPPER'), ('SNACK', 'SNACK')], max_length=128),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='title',
            field=models.CharField(choices=[('KCal', 'KCal'), ('Total Fat', 'Total Fat'), ('Saturated FatMonounsaturated Fat', 'Saturated FatMonounsaturated Fat'), ('Polyunsaturated Fat', 'Polyunsaturated Fat'), ('Total trans fatty acids', 'Total trans fatty acids'), ('Total trans-monoenoic fatty acids', 'Total trans-monoenoic fatty acids'), ('Total trans-polyenoic fatty acids', 'Total trans-polyenoic fatty acids'), ('Total Omega-3 fatty acids', 'Total Omega-3 fatty acids'), ('Total Omega-6 fatty acids', 'Total Omega-6 fatty acids'), ('Total carbohydrate', 'Total carbohydrate'), ('Added sugars', 'Added sugars'), ('Dietary fiber', 'Dietary fiber'), ('Vitamin A', 'Vitamin A'), ('Vitamin C', 'Vitamin C'), ('Vitamin D', 'Vitamin D'), ('Vitamin E', 'Vitamin E'), ('Vitamin K', 'Vitamin K'), ('Thiamin (vitamin B1)', 'Thiamin (vitamin B1)'), ('Riboflavin (vitamin B2)', 'Riboflavin (vitamin B2)'), ('Niacin (vitamin B3)', 'Niacin (vitamin B3)'), ('Pyridoxine (vitamin B6)', 'Pyridoxine (vitamin B6)'), ('Folate', 'Folate'), ('Cobalamine (vitamin B12)', 'Cobalamine (vitamin B12)'), ('Biotin', 'Biotin'), ('Pantothenic acid (vitamin B5)', 'Pantothenic acid (vitamin B5)'), ('Calcium', 'Calcium'), ('Iron', 'Iron'), ('Phosphorus', 'Phosphorus'), ('Iodine', 'Iodine'), ('Magnesium', 'Magnesium'), ('Zinc', 'Zinc'), ('Selenium', 'Selenium'), ('Copper', 'Copper'), ('Manganese', 'Manganese'), ('Protein', 'Protein')], max_length=128),
        ),
    ]
