# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20170404_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='GenericDishNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_100_gr', models.FloatField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_nutrients', to='food.GenericDish')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Nutrient')),
            ],
        ),
        migrations.RenameModel(
            old_name='GrammsOfIngredientPerUnit',
            new_name='GramsOfIngredientPerUnit',
        ),
    ]
