# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20170405_0810'),
        ('food', '0008_auto_20170404_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericdish',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='genericdishnutrient',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='genericdishnutrient',
            name='nutrient',
        ),
        migrations.DeleteModel(
            name='GenericDish',
        ),
        migrations.DeleteModel(
            name='GenericDishNutrient',
        ),
    ]
