# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 06:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20170609_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='preparation',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='preparation_html',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='nutrients_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
