# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20170613_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
