# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
        ('food', '0016_auto_20170613_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(related_name='dishes', to='tagging.Tag'),
        ),
    ]
