# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0017_dish_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='serving',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='tagging.Tag'),
        ),
    ]
